version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app_test
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress1
      WORDPRESS_DB_PASSWORD: wordpress1
      WORDPRESS_DB_NAME: wordpress1
    volumes:
      - ./wordpress1:/var/www/html

  db:
    image: mariadb:latest
    container_name: wordpress_db_test
    restart: always
    environment:
      MYSQL_DATABASE: wordpress1
      MYSQL_USER: wordpress1
      MYSQL_PASSWORD: wordpress1
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./db_data1:/var/lib/mysql
